using SensorsMaster.AppSettings;
using System;
using Newtonsoft.Json;

namespace SensorsMaster.Device.Model
{
    public abstract class BoardElement
    {
        #region Properties
        [JsonIgnore]
        public Settings Settings => Settings.GetInstance();

        /// <summary>
        /// Autogenerated. Starts at 0.
        /// </summary>
        public int Id { get; set; }
        public Coordinates Coordinates { get; set; } 
        #endregion

        #region Constructors
        public BoardElement()
        {
            Coordinates = new Coordinates(0, 0);
        }
        public BoardElement(Coordinates coordinates) : this()
        {
            Coordinates = coordinates;
        }
        public BoardElement(double x, double y) : this(new Coordinates(x, y))
        { }
        #endregion

        #region Methods
        public double Distance(BoardElement element)
        {
            return this.Coordinates.Distance(element.Coordinates);
        } 
        #endregion
    }
}
