using SensorsMaster.AppSettings;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Xml.Serialization;

namespace SensorsMaster.Device.Model
{
    [XmlRoot(nameof(BoardElement), IsNullable = false)]
    public abstract class BoardElement
    {
        #region Properties
        [XmlIgnore]
        public Settings Settings => Settings.GetInstance();

        /// <summary>
        /// Autogenerated. Starts at 0.
        /// </summary>
        [XmlAttribute]
        public int Id { get; set; }
        [XmlElement]
        public Coordinates Coordinates { get; set; } 
        #endregion

        #region Constructors
        public BoardElement()
        {
            Coordinates = new Coordinates(0, 0);
        }
        public BoardElement(Coordinates coordinates) : this()
        {
            Coordinates = coordinates;
        }
        public BoardElement(double x, double y) : this(new Coordinates(x, y))
        { }
        #endregion

        #region Methods
        public double Distance(BoardElement element)
        {
            return this.Coordinates.Distance(element.Coordinates);
        } 
        #endregion
    }
}
